version: "3.7"

services:
# Mengatur service untuk container item-db
  item-db:
    image: mongo:3
    restart: always
    volumes:
      - app-db:/data/db

#  mengatur service untuk container item-app
  item-app:
    image: maftuh23/item-app:v1
    depends_on:
      - item-db
    restart: always
    ports :
      - 80:8080

# Mengatur volume untuk container item-db
volumes:
  app-db: